[package]
name = "rocket-demo"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
rocket_contrib = "0.4.5"
couchbase = "1.0.0-alpha.4"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"