name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: 1 
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Couchbase Dependencies - 1
      run: sudo apt-key add /home/runner/work/rocket-demo/rocket-demo/couchbase.key
    - name: Install Couchbase Dependencies - 2
      run: sudo cp /home/runner/work/rocket-demo/rocket-demo/couchbase.list /etc/apt/sources.list.d/couchbase.list
    - name: Install Couchbase Dependencies - 3
      run: sudo apt update && sudo apt install -y libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent libev-dev libevent-dev
    - name: Couchbase check
      run: cbc version
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --all --release && strip target/release/actix_demo && mv target/release/actix_demo target/release/actix_demo_amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "0.1.0"
        files: target/release/actix_demo_amd64
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
