name: Rust

on:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: 1 
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: himanshumps/rust-musl-action@master
      with:
        args: cargo +stable build --release
    - name: Cleaning
      run: ls -altr target/release/a* && strip target/release/actix_demo && mv target/release/actix_demo target/release/actix_demo_amd64
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: "0.1.0"
        delete_release: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "0.1.0"
        prerelease: true
        files: target/release/actix_demo_amd64
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
