name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: 1 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Couchbase Dependencies - 1
      run: sudo apt-key add /home/runner/work/rocket-demo/rocket-demo/couchbase.key
    - name: Install Couchbase Dependencies - 2
      run: sudo cp /home/runner/work/rocket-demo/rocket-demo/couchbase.list /etc/apt/sources.list.d/couchbase.list
    - name: Install Couchbase Dependencies - 3
      run: sudo apt update && apt install -y libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
