name: Rust

on:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: 1 
      PKG_CONFIG_ALLOW_CROSS: 1
      #CXX: /usr/bin/clang++
      #CC: /usr/bin/clang
      RUSTFLAGS: -Clinker=musl-gcc
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Couchbase Dependencies - 1
      run: sudo apt-key add /home/runner/work/rocket-demo/rocket-demo/couchbase.key
    - name: Install Couchbase Dependencies - 2
      run: sudo cp /home/runner/work/rocket-demo/rocket-demo/couchbase.list /etc/apt/sources.list.d/couchbase.list
    - name: Install Couchbase Dependencies - 3
      run: sudo apt update && sudo apt install -y libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent libev-dev libevent-dev
    - name: Install bindgen
      run: sudo apt install llvm-dev libclang-dev clang musl-tools libssl-dev pkg-config build-essential
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install target
      run: rustup target add x86_64-unknown-linux-musl
    #- name: clang changes
    #  run: sudo update-alternatives --config c++
    - name: Build
      run: cargo build --all --release --target x86_64-unknown-linux-musl && ls -altr target/x86_64-unknown-linux-musl/release/a* && strip target/x86_64-unknown-linux-musl/release/actix_demo && mv target/x86_64-unknown-linux-musl/release/actix_demo target/release/actix_demo_amd64
      env:
        PKG_CONFIG_ALLOW_CROSS: 1
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: "0.1.0"
        delete_release: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "0.1.0"
        prerelease: true
        files: target/release/actix_demo_amd64
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
